# Generated by Django 4.2.11 on 2024-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0005_equipment_remove_observation_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sky_conditions',
        ),
    ]
