# Generated by Django 4.2.11 on 2024-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0007_observation_sky_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proper_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('hip', models.IntegerField()),
                ('bayer', models.CharField(max_length=255)),
                ('origin', models.TextField()),
                ('ethnic_cultural_group', models.CharField(blank=True, max_length=255)),
                ('reference', models.TextField()),
                ('additional_info', models.TextField(blank=True)),
                ('approval_status', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
        ),
    ]
