# Generated by Django 4.2.11 on 2024-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0009_alter_star_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='additional_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='star',
            name='hip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='star',
            name='origin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='star',
            name='reference',
            field=models.CharField(max_length=255),
        ),
    ]
