# Generated by Django 4.2.11 on 2024-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
