# Generated by Django 4.2.11 on 2024-04-22 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('observation_time', models.DateTimeField()),
                ('sky_conditions', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('personal_observations', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
