# Generated by Django 4.2.11 on 2024-05-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0006_skycondition_remove_observation_sky_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='sky_conditions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polaris.skycondition'),
            preserve_default=False,
        ),
    ]
