# Generated by Django 4.2.11 on 2024-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0008_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='approval_date',
            field=models.CharField(max_length=255),
        ),
    ]
