# Generated by Django 4.2.11 on 2024-05-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0012_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
