# Generated by Django 4.2.11 on 2024-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0013_remove_user_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='privacy',
            field=models.IntegerField(default=1),
        ),
    ]
