# Generated by Django 4.2.11 on 2024-06-06 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0017_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polaris.event'),
        ),
    ]
