# Generated by Django 4.2.11 on 2024-06-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0021_notification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
