# Generated by Django 4.2.11 on 2024-06-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0023_chat_constellation_planet_message_star_constellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polaris.event'),
        ),
    ]
